Adding retry script

diff --git a/bash/aliases b/bash/aliases
--- a/bash/aliases
+++ b/bash/aliases
@@ -28,6 +28,31 @@ function replace {
   fi
 }
 
+function fail {
+  echo $1 >&2
+  exit 1
+}
+
+# Re-rerun a command 5 times
+function retry {
+  local n=1
+  local max=5
+  local delay=15
+  while true; do
+    "$@" && break || {
+      if [[ $n -lt $max ]]; then
+        ((n++))
+        echo "Command failed. Attempt $n/$max:"
+        sleep $delay;
+      else
+        fail "The command has failed after $n attempts."
+      fi
+    }
+  done
+}
+
+retry bundle install
+
 # whitespace: remove trailing whitespace
 #     example: whitespace *.rb
 function whitespace {
